---
title: "Box Apps"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{box-apps}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Apps

Apps are what allow you to interact programatically with the Box API. They are created and manage them through [Box's developer console](https://app.box.com/developers/console), either by you or by your institution's Box-admin team. If you've already used `boxr` to authenticate with Box, you've already used a Box app. This vignette is about the differences between the two type of apps that `boxr` uses and the security considerations that go along with them.

## Standard OAuth2 (User Authentication)

An OAuth2 app is strightforward because it acts on behalf of the user who has authenticated to it, with all the privileges of that user. To authenticate using an OAuth2 app, you can use the `box_auth()` function.

More than one user can authenticate to and use a given app; however, each user will be able to use the app only as themself. There is a restriction: a Box app can handle no more than one request at a time; the greater the number of users of a given app, the greater the probability of a collision.

The authentication process for an OAuth2 app is easiest if you have physical control of the computer from which you are trying to authenticate, e.g. your laptop. The token retrieved by `box_auth()` is as "powerful" as the user themself; it should be treated with appropriate care. The user's Box account is no more secure than the security of the token on their computer.

By default, the `boxr` token is cached, unencrypted, in the user's home directory: `~/boxr-oauth`. As it is unencrypted, this file should not be committed to a git repository.

This is the first choice for authentication, and should be enough for most `boxr` users. More details on using and creating an OAuth2 app are given in its [vignette](./auth-oauth2.html).

## OAuth2.0 with JWT (Server Authentication)

The second choice for authentication, when you don't have access to a local browser. These apps have elevated permissions and require Box adminstrator approval becasue of it. 

This type of app is represented with a *service* account, which is associated with a Box enterprise. A service account is similar to a user account, but with additional admin functionality. Service accounts are not linked to a particular user account and they have their own separate file storage system.

JWT apps are primarily designed for sys-admin work, but they are useful to `boxr`, because they can assume the identify of an existing user and they play well on remotes. Becasue of how Box structured their API for these apps, they are capable of performining actions as *any non-admin user* within its associated enterprise. Currently there is [no way to restrict app abilities/access to only specific users](https://community.box.com/t5/Platform-and-Development-Forum/Restrict-service-account-permissions-to-specific-users/td-p/35984). `boxr` only supports acting as a individual users and does not provide access to other admin level functionality, like creating/deleting users, managing document permissions, etc.

If you are setting a JWT app up for a personal account, this is not really an issue. But if you are doing this for a company account, this means the app *could* access sensitive information from another user account (eg payroll, HR records, etc.) if it was provided with the relevant user ID and a valid private key file. Note: Box provisions user IDs by time the account was created, so if a batch of accounts was created together (say when the enterprise account was initialized) they will have sequential user ID numbers.
