---
title: "Box Apps"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{boxr-apps}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Apps

Apps are what allow you to interact programatically with the Box API. 
They are created and managed using [Box's developer console](https://app.box.com/developers/console), either by you or by your institution's Box-admin team. If you've already used `boxr` to authenticate with Box, you've already used a Box app. 

This vignette is about the two types of apps that `boxr` uses, how to authenticate to them, and the security considerations that go along with them:

- Interactive App [[vignette](./boxr-app-interactive.html)]: This is preferred for interactive use (this includes you hitting the "knit" button in the RStudio IDE). The user authenticates to the app interactively, using the "OAuth Dance": a browser-window is opened to ask the user's permission. The app has all the rights of the user who authenticates to it.

- Service App [[vignette](./boxr-app-service.html)]: This is useful for unattended use, e.g. on a remote computer. A token (JSON file) is generated using the Box (or Box Enterprise) website. This token can be deployed to the (presumably remote) computer; there is no "OAuth Dance". Becuase these apps can act on behalf of the Box system itself, we recommend that you configure the app with a *minimal* set of privleges, e.g. to access only the Box folder that the app will need.

## Interactive App

An interactive-app is strightforward because it acts on behalf of the user who has authenticated to it, with all the privileges of that user. To authenticate using an OAuth2 app, you can use the `box_auth()` function, which may invoke the "OAuth Dance".

More than one user can authenticate to and use a given app; however, each user will be able to use the app only as themself. There is a restriction: a Box app can handle no more than one request at a time; the greater the number of users of a given app, the greater the probability of a collision.

The authentication process for an interactive-app is easiest if you have physical control of the computer from which you are trying to authenticate, e.g. your laptop. If you are using a remote computer, e.g. RStudio Server, you can generate this token on a local computer, then upload the token to your RStudio Server. 

Keep in mind that the token retrieved by `box_auth()` is as "powerful" as the user themself; it should be treated with all due care. The user's Box account is no more secure than the security of this token. By default, the `boxr` token is cached, unencrypted, in the user's home directory, as `~/boxr-oauth`. Because it is unencrypted, you should take care not to commit this file to a git repository.

We recommend this as the first choice for authentication; it should work well in most situations, for most `boxr` users. More details on using and creating an interactive-app are given in [its vignette](./boxr-app-interactive.html).

## Service App

There may be situations you want to use `boxr` as a part of specific unattended tasks. Perhaps it is a scheduled report, perhaps a set of continuous-integration tests. Service-apps are designed for these situations, but they should be used with care - particulary because they are designed to run unattended, outside your daily attention.

This type of app uses a *service* account, which is associated with a Box account or a Box Enterprise account. A service account is similar to a user account, but with additional admin functionality. Service accounts are not linked to a particular user account, but they can be configured to act on behalf of **any and all** user accounts for that Box account. Hence, they have additional security considerations. 

You can mitigate this security consideration by restricting the capability of a service-app so that its service-account can access **only** a particular folder. Although it may be administratively-cumbersome, you might consider a separate service-app for each use-case. This way, if a token becomes comprised, the exposure is limited to that folder, that use-case.

The authentication-process for a JWT app is handled at the Box (or Box Enterprise) website, in an admin-console. Here, you can generate a token for your app, then download it so that you can deploy it for your use-case. You can do this *once*, in contrast with the "OAuth Dance" you need to undertake, from time-to-time, with a standard OAuth2 app.

A service-app, using JWT authentication, can work for unattended tasks, but please take care to give your app as *little* capability as needed. More details on using and creating a service-app are given in [its vignette](./boxr-app-service.html).
